---

directories:
  temp_dir: 'temp'
  save_dir: 'recordings'

udp:
  ip_address: "0.0.0.0"
  send_port: 7001
  recv_port: 7000
  id_length: 15
  timeout: 15

audio:
  rate: 16000 # Hz
  sample_width: 2 # bytes
  channels: 1
  file_duration: 5 # seconds

processes:
  - name: anomalies
    position: input
    type: anomaly
    model: 'models/cae16k.tflite'
    config:
      threshold: 0.04 #53
      input_shape: [5, 16000, 1]
      preprocess: null
    log: default
    actions:
      always:
        - action: output
      on_result:
        - true>0:
            action: next
            input: same
            target: yamnet

  - name: yamnet
    type: classification
    model: 'models/yamnet.tflite'
    config:
      labels: 'models/labels/yamnet.csv'
      minimum_confidence: 0.6
      count: 3
      input_shape: [80000] # = 5 * 16000
      preprocess: null
    log: 'Process %n -> Results : %R' # null
    actions:
      on_not_result:
        - silence>=100%:
            action: null
      always: 
        - action: output
        - action: save
          filename: '%d;%r;%a.wav'
          directory: default
